name: Generate Subscription

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 运行, 你可以根据需要修改 cron 表达式

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'

      - name: Download subs-check binary
        run: |
          # 获取最新的 release 版本号 (简单方法，可能需要更健壮的逻辑)
          VERSION=$(curl -s https://api.github.com/repos/beck-8/subs-check/releases/latest | jq -r.tag_name)
          echo "Downloading version: $VERSION"
          wget "https://github.com/beck-8/subs-check/releases/download/${VERSION}/subs-check_Linux_x86_64.tar.gz"
          tar -xzf subs-check_Linux_x86_64.tar.gz
          chmod +x subs-check

      - name: Run subs-check and generate subscription
        run: |
         ./subs-check > subscription.txt

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '自动更新订阅列表'
          file_pattern: subscription.txt
