name: Run subs-check

on:
  schedule:
    - cron: '15 17 * * *' # 每天 UTC 时间 17:15 运行
  workflow_dispatch:

jobs:
  run-subs-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Replace placeholders in config.yaml
        run: |
          sed -i 's|__GIST_ID_PLACEHOLDER__|${{ secrets.GIST_ID }}|g' config.yaml
        env:
          GIST_ID: ${{ secrets.GIST_ID }}

      - name: Run subs-check and Upload to Gist
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_PAT }}
        run: |
          echo "Running subs-check..."
          docker run --rm \
            -v ${{ github.workspace }}/config.yaml:/app/config/config.yaml \
            -v ${{ github.workspace }}/output:/app/output \
            -e GITHUB_TOKEN \
            ghcr.io/beck-8/subs-check:latest
          echo "subs-check finished."
